//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TravailLigueEntities : DbContext
    {
        public TravailLigueEntities()
            : base("name=TravailLigueEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tcategory> tcategories { get; set; }
        public virtual DbSet<tcompte> tcomptes { get; set; }
        public virtual DbSet<tligue> tligues { get; set; }
        public virtual DbSet<treserv> treservs { get; set; }
        public virtual DbSet<tsalle> tsalles { get; set; }
    }
}
