//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tsalle
    {
        public tsalle()
        {
            this.treservs = new HashSet<treserv>();
        }
    
        public short idsalle { get; set; }
        public string libsalle { get; set; }
        public decimal prixsalle { get; set; }
        public short perssalle { get; set; }
        public short idCat { get; set; }
    
        public virtual tcategory tcategory { get; set; }
        public virtual ICollection<treserv> treservs { get; set; }
    }
}
