//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tcategory
    {
        public tcategory()
        {
            this.tsalles = new HashSet<tsalle>();
        }
    
        public short idCat { get; set; }
        public string libcat { get; set; }
    
        public virtual ICollection<tsalle> tsalles { get; set; }
    }
}
