//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tligue
    {
        public tligue()
        {
            this.treservs = new HashSet<treserv>();
        }
    
        public int idligue { get; set; }
        public string nomligue { get; set; }
        public string adrligue { get; set; }
        public string villeligue { get; set; }
        public string cpligue { get; set; }
        public string telligue { get; set; }
        public string mailligue { get; set; }
        public string intitligue { get; set; }
    
        public virtual ICollection<treserv> treservs { get; set; }
    }
}
