//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class treserv
    {
        public int idreserv { get; set; }
        public int idLigue { get; set; }
        public short idsalle { get; set; }
        public System.DateTime datereserv { get; set; }
    
        public virtual tligue tligue { get; set; }
        public virtual tsalle tsalle { get; set; }
    }
}
